version: '3.7'
services:
  db:
    image: mysql:8.0
    container_name: "make-friends-db"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      
  api:
    build: ./api
    container_name: "make-friends-api"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  view:
    build: ./view
    command: npm run serve
    container_name: "make-friends-view"
    ports:
      - "8080:8080"
    volumes:
      - ./view:/app
    stdin_open: true
    tty: true
    environment:
      - VUE_APP_URL=http://localhost:3000
    depends_on:
      - api

volumes:
  mysql-data:
    driver: local
